services:
    app.websocket.service.connection.manager:
        public: true
        class: App\WebsocketBundle\Service\ConnectionManager
        arguments:    ['@service_container']

    app.websocket.service.routing.manager:
        class: App\WebsocketBundle\Service\RoutingManager
        arguments:    ['@service_container']

    app.websocket.console.start:
        class: App\WebsocketBundle\Console\StartCommand
        tags:
            -  { name: console.command }
